name: linux-cpanm-test
on: [push, pull_request]
jobs:
  build-dist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: perl info
        run: |
          perl --version
      - name: setup locallib
        run: |
          PERL_LOCAL_LIB_ROOT="$HOME/perl5"
          >>"$GITHUB_ENV" echo "PERL_LOCAL_LIB_ROOT=$PERL_LOCAL_LIB_ROOT"
          >>"$GITHUB_ENV" echo "PERL5LIB=$PERL_LOCAL_LIB_ROOT/lib/perl5"
          >>"$GITHUB_ENV" echo "PERL_MB_OPT=--install_base \"$PERL_LOCAL_LIB_ROOT/\""
          >>"$GITHUB_ENV" echo "PERL_MM_OPT=INSTALL_BASE=$PERL_LOCAL_LIB_ROOT"
          >>"$GITHUB_ENV" echo "PATH=$PERL_LOCAL_LIB_ROOT/bin:$PATH"
      - name: install cpanm
        run: cpan App::cpanminus
      - name: test cpanm
        run: cpanm -v Path::Tiny
